CREATE SCHEMA IF NOT EXISTS mentedge;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS mentedge.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  gender TEXT,
  date_of_birth DATE,
  avatar TEXT,
  phone_number TEXT,
  bio TEXT,
  current_city TEXT,
  current_state TEXT,
  current_status TEXT,
  resume_link TEXT,
  portfolio_link TEXT,
  linkedin_link TEXT,
  github_link TEXT,
  hear_about TEXT,
  educations JSONB,
  experience JSONB,
  skills JSONB,
  languages JSONB,
  certificates JSONB,
  interests JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mentedge.mentors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'mentor',
  gender TEXT,
  date_of_birth DATE,
  avatar TEXT,
  phone_number TEXT,
  bio TEXT,
  current_city TEXT,
  current_state TEXT,
  current_status TEXT,
  resume_link TEXT,
  portfolio_link TEXT,
  linkedin_link TEXT,
  github_link TEXT,
  hear_about TEXT,
  educations JSONB,
  experience JSONB,
  skills JSONB,
  languages JSONB,
  certificates JSONB,
  interests JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
